=== iyourshaw/jpo-geojsonconverter/jpo-geojsonconverter/src/main/resources/schemas/processed-spat.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://raw.githubusercontent.com/usdot-jpo-ode/jpo-geojsonconverter/develop/jpo-geojsonconverter/src/main/resources/schemas/processed-spat.schema.json",
    "type": "object",
    "properties": {
        "messageType": {
            "type": "string",
            "const": "SPAT"
        },
        "odeReceivedAt": {
            "type": "string",
            "format": "date-time"
        },
        "utcTimeStamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp derived from the timestamp=DE_MinuteOfTheYear of the top level of the spat message and the timeStamp=DE_Dsecond of the IntersectionState."
        },
        "originIp": {
            "$ref": "#/$defs/IPAddress"
        },
        "name": {
            "oneOf": [
                { "$ref": "spat.schema.json#/$defs/J2735DescriptiveName" },
                { "type": "null" }
            ]
        },
        "region": {
            "$ref": "spat.schema.json#/$defs/J2735RoadRegulatorID"
        },
        "intersectionId": {
            "$ref": "spat.schema.json#/$defs/J2735IntersectionID"
        },
        "cti4501Conformant": {
            "type": "boolean"
        },
        "validationMessages": {
            "$ref": "#/$defs/ValidationMessageList"
        },
        "revision": {
            "$ref": "spat.schema.json#/$defs/J2735MsgCount"
        },
        "status": {
            "$ref": "spat.schema.json#/$defs/J2735IntersectionStatusObject"
        },
        "enabledLanes": {
            "$ref": "spat.schema.json#/$defs/J2735EnabledLaneList",
            "description": "Conditionally required"
        },
        "states": {
            "$ref": "#/$defs/MovementList"
        }
    },
    "required": [
        "messageType",
        "odeReceivedAt",
        "utcTimeStamp",
        "originIp",
        "region",
        "intersectionId",
        "cti4501Conformant",
        "revision",
        "status",
        "enabledLanes",
        "states"
    ],
    "additionalProperties": false,
    "$defs": {
        "MovementList": {
            "type": "array",
            "minItems": 1,
            "maxItems": 255,
            "items": {
                "$ref": "#/$defs/MovementState"
            }
        },
        "MovementState": {
            "type": "object",
            "properties": {
                "movementName": {
                    "oneOf": [
                        { "$ref": "spat.schema.json#/$defs/J2735DescriptiveName" },
                        { "type": "null" }
                    ]
                },
                "signalGroup": {
                    "$ref": "#/$defs/J2735SignalGroupID"
                },
                "stateTimeSpeed": {
                    "$ref": "#/$defs/MovementEventList"
                },
                "maneuverAssistList": {
                    "oneOf": [ 
                        { "type": "null" }, 
                        { "type": "object" } 
                    ]
                }
            },
            "required": [
                "signalGroup",
                "stateTimeSpeed"
            ],
            "additionalProperties": false
        },
        "MovementEventList": {
            "type": "array",
            "minItems": 1,
            "maxItems": 16,
            "items": {
                "$ref": "#/$defs/MovementEvent"
            }
        },
        "MovementEvent": {
            "type": "object",
            "properties": {
                "eventState": {
                    "$ref": "spat.schema.json#/$defs/J2735MovementPhaseState"
                },
                "timing": {
                    "$ref": "#/$defs/TimeChangeDetails",
                    "description": "Optional in J2735, but mandatory in CI Implementation Guide"
                },
                "speeds": {
                    "oneOf": [
                        {
                            "$ref": "spat.schema.json#/$defs/J2735AdvisorySpeedList"
                        },
                        { "type": "null" }
                    ]
                }
            },
            "required": [
                "eventState",
                "timing"
            ],
            "additionalProperties": false
        },
        "TimeChangeDetails": {
            "type": "object",
            "description": "Derived from J2735TimeChangeDetails with DE_TimeMark fields converted to UTC strings",
            "properties": {
                "startTime": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Optional in J2735, but mandatory in CI Implementation Guide"
                },
                "minEndTime": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Mandatory in both J2735 and CI Guide"
                },
                "maxEndTime": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Optional in J2735, but mandatory in CI Implementation Guide"
                },
                "likelyTime": {
                    "oneOf": [
                        {
                            "type": "string",
                            "format": "date-time"
                        },
                        { "type": "null" }
                    ],
                    "description": "Optional"
                },
                "confidence": {
                    "oneOf": [
                        {
                            "type": "integer",
                            "minimum": 0,
                            "maximum": 15
                        },
                        { "type": "null" }
                    ],
                    "description": "DE_TimeIntervalConfidence. Optional."
                },
                "nextTime": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Optional in J2735, but mandatory in CI Implementation Guide"
                }
            },
            "required": [
                "startTime",
                "minEndTime",
                "maxEndTime",
                "nextTime"
            ],
            "additionalProperties": false
        },
        "ValidationMessageList": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/ValidationMessage"
            },
            "minItems": 0,
            "description": "A list of validation messages"
        },
        "ValidationMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "description": "Description/summary of the validation error"
                },
                "jsonPath": {
                    "type": "string",
                    "description": "Path in the original ODE JSON message"
                },
                "schemaPath": {
                    "type": "string",
                    "description": "Path in the json schema of the ODE JSON"
                },
                "exception": {
                    "type": "string",
                    "description": "Details of java validation exception thrown, if any"
                }
            },
            "required": [
                "message"
            ]
        },
        "IPAddress": {
            "oneOf": [
                { 
                    "type": "string",
                    "format": "ipv4"
                },
                { 
                    "type": "string",
                    "format": "ipv6"
                }
            ]
        },
        "J2735SignalGroupID": {
            "type": "integer",
            "minimum": 0,
            "maximum": 255,
            "description": "DE_SignalGroupID"
        }
    }
}

=== iyourshaw/jpo-geojsonconverter/jpo-geojsonconverter/src/test/resources/json/sample.processed-spat.json
{
    "messageType": "SPAT",
    "odeReceivedAt": "2022-11-17T22:55:16.330328Z",
    "originIp": "172.18.0.1",
    "region": 0,
    "intersectionId": 12110,
    "cti4501Conformant": false,
    "validationMessages": [
      {
        "message": "$.payload.data.timeStamp: null found, integer expected",
        "jsonPath": "$.payload.data.timeStamp",
        "schemaPath": "#/$defs/J2735MinuteOfTheYear/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].id.region: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].id.region",
        "schemaPath": "#/$defs/J2735RoadRegulatorID/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].status: string found, object expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].status",
        "schemaPath": "#/$defs/J2735IntersectionStatusObject/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[0].state_time_speed.movementEventList[0].timing.startTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[0].state_time_speed.movementEventList[0].timing.startTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[0].state_time_speed.movementEventList[0].timing.nextTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[0].state_time_speed.movementEventList[0].timing.nextTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[1].state_time_speed.movementEventList[0].timing.startTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[1].state_time_speed.movementEventList[0].timing.startTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[1].state_time_speed.movementEventList[0].timing.nextTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[1].state_time_speed.movementEventList[0].timing.nextTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[2].state_time_speed.movementEventList[0].timing.startTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[2].state_time_speed.movementEventList[0].timing.startTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[2].state_time_speed.movementEventList[0].timing.nextTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[2].state_time_speed.movementEventList[0].timing.nextTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[3].state_time_speed.movementEventList[0].timing.startTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[3].state_time_speed.movementEventList[0].timing.startTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[3].state_time_speed.movementEventList[0].timing.nextTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[3].state_time_speed.movementEventList[0].timing.nextTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[4].state_time_speed.movementEventList[0].timing.startTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[4].state_time_speed.movementEventList[0].timing.startTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[4].state_time_speed.movementEventList[0].timing.nextTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[4].state_time_speed.movementEventList[0].timing.nextTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[5].state_time_speed.movementEventList[0].timing.startTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[5].state_time_speed.movementEventList[0].timing.startTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[5].state_time_speed.movementEventList[0].timing.nextTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[5].state_time_speed.movementEventList[0].timing.nextTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[6].state_time_speed.movementEventList[0].timing.startTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[6].state_time_speed.movementEventList[0].timing.startTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[6].state_time_speed.movementEventList[0].timing.nextTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[6].state_time_speed.movementEventList[0].timing.nextTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[7].state_time_speed.movementEventList[0].timing.startTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[7].state_time_speed.movementEventList[0].timing.startTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      },
      {
        "message": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[7].state_time_speed.movementEventList[0].timing.nextTime: null found, integer expected",
        "jsonPath": "$.payload.data.intersectionStateList.intersectionStatelist[0].states.movementList[7].state_time_speed.movementEventList[0].timing.nextTime",
        "schemaPath": "#/$defs/J2735TimeMark/type"
      }
    ],
    "revision": 0,
    "status": {
      "manualControlIsEnabled": true,
      "stopTimeIsActivated": false,
      "failureFlash": false,
      "preemptIsActive": false,
      "signalPriorityIsActive": false,
      "fixedTimeOperation": false,
      "trafficDependentOperation": false,
      "standbyOperation": false,
      "failureMode": false,
      "off": false,
      "recentMAPmessageUpdate": false,
      "recentChangeInMAPassignedLanesIDsUsed": false,
      "noValidMAPisAvailableAtThisTime": false,
      "noValidSPATisAvailableAtThisTime": false
    },
    "utcTimeStamp": "2022-11-17T22:55:28.744Z",
    "enabledLanes": [],
    "states": [
      {
        "signalGroup": 1,
        "stateTimeSpeed": [
          {
            "eventState": "STOP_AND_REMAIN",
            "timing": {
              "startTime": null,
              "minEndTime": "2022-11-17T22:03:48.1Z",
              "maxEndTime": "2022-11-17T22:03:48.1Z",
              "likelyTime": null,
              "confidence": 0,
              "nextTime": null
            }
          }
        ]
      },
      {
        "signalGroup": 2,
        "stateTimeSpeed": [
          {
            "eventState": "STOP_AND_REMAIN",
            "timing": {
              "startTime": null,
              "minEndTime": "2022-11-17T22:03:05.1Z",
              "maxEndTime": "2022-11-17T22:03:05.1Z",
              "likelyTime": null,
              "confidence": 0,
              "nextTime": null
            }
          }
        ]
      },
      {
        "signalGroup": 3,
        "stateTimeSpeed": [
          {
            "eventState": "STOP_AND_REMAIN",
            "timing": {
              "startTime": null,
              "minEndTime": "2022-11-17T22:03:48.1Z",
              "maxEndTime": "2022-11-17T22:03:48.1Z",
              "likelyTime": null,
              "confidence": 0,
              "nextTime": null
            }
          }
        ]
      },
      {
        "signalGroup": 4,
        "stateTimeSpeed": [
          {
            "eventState": "STOP_AND_REMAIN",
            "timing": {
              "startTime": null,
              "minEndTime": "2022-11-17T22:02:38.1Z",
              "maxEndTime": "2022-11-17T22:02:38.1Z",
